"""Validate PDFs generated by test-impressao-comprovantes.cjs. Optional --render saves page PNGs."""
import sys
from pathlib import Path
from pypdf import PdfReader

folder = Path(sys.argv[1])
files = list(folder.glob('*.pdf'))
assert len(files) >= 8, 'Gere todos os comprovantes antes de validar.'
for path in files:
    reader = PdfReader(path)
    texts = [page.extract_text() or '' for page in reader.pages]
    assert all(len(text.strip()) > 40 for text in texts), (path, 'Página vazia')
    text = '\n'.join(texts)
    assert 'CONTEUDO ATRAS DO MODAL' not in text, path
    if path.name.startswith('recibo'):
        assert text.count('TESTE RECIBO FINAL') == 1, path
        assert 'Ordem de cobrança' not in text, path
        assert text.count('TOTAL REGISTRADO') == 1, path
    if path.name == 'venda-duas-paginas.pdf':
        assert len(texts) == 2
        assert 'VALOR TOTAL' not in texts[0]
        assert texts[-1].count('VALOR TOTAL') == 2
        assert texts[-1].count('16 M') == 2
    if path.name == 'venda-mista.pdf':
        assert len(texts) == 1
        assert text.count('5 M E 2 UN') == 2
    if '--render' in sys.argv:
        import pypdfium2 as pdfium
        document = pdfium.PdfDocument(path)
        for i in range(len(document)):
            document[i].render(scale=1.3).to_pil().save(path.with_name(f'{path.stem}-{i+1}.png'))
    print(f'OK: {path.name}: {len(texts)} página(s), conteúdo e totais preservados')
